# K8S 이전 하기전 DT 서비스들에 필요힌 인프라 관련 컨테이너들 서버 PC 에 배포하기 위한 docker-compose 파일
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
      
  flask_screen_capture:
    build: .
    container_name: flask_screen_capture
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - CAPTURE_INTERVAL=1.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
    ports:
      - "5000:5000"
  power_info:
    build: .
    container_name: power_info
    privileged: true
    network_mode: "host"
    environment:
      - FLASK_APP=power_info.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ${HOME}/.kube/config:/root/.kube/config:ro
    ports:
      - "5001:5000"