[package]
version = "1.0.0"
authors = ["NetAI", "CosmoAdAstra"]
title = "NetAI Cesium Digital Twin"
description = "Real-time digital twin system that synchronizes Omniverse Cesium objects with web-based 2D maps via WebSocket communication."
readme = "docs/README.md"
repository = "https://github.com/NetAI/Omniverse-Cesium-DigitalTwin"
category = "Simulation"
keywords = ["cesium", "digital-twin", "websocket", "real-time", "tracking"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
# Core UI dependencies
"omni.ui" = {}

# USD and scene dependencies  
"omni.usd" = {}
"omni.kit.selection" = {}
# Stage UI (updated for Kit SDK >= 105)
"omni.kit.window.stage" = {}

# Cesium dependency
"cesium.omniverse" = {}

# Main python module
[[python.module]]
name = "netai.cesium.digitaltwin"

[extension]
enabled = false
order = 100

[python.pipapi]
requirements = [
    "websockets>=11.0.3",
    "pydantic>=2.0.0"
]
use_online_index = true

[settings]
# Extension settings that can be configured by users
exts."netai.cesium.digitaltwin".websocket_url = "ws://localhost:8000/ws"
exts."netai.cesium.digitaltwin".update_interval = 1.0
exts."netai.cesium.digitaltwin".auto_connect = true
exts."netai.cesium.digitaltwin".debug_mode = false
exts."netai.cesium.digitaltwin".tracked_objects = ["/World/Husky_01", "/World/Husky_02"]

# UI settings
exts."netai.cesium.digitaltwin".show_window_on_startup = true
exts."netai.cesium.digitaltwin".window_width = 400
exts."netai.cesium.digitaltwin".window_height = 600

# Logging settings
exts."netai.cesium.digitaltwin".log_level = "INFO"
exts."netai.cesium.digitaltwin".log_websocket_messages = false