ouster/os_driver:
  ros__parameters:
    # --- 필수 네트워크 설정 ---
    sensor_hostname: "192.168.131.20"
    udp_dest: "192.168.131.1"

    # 이 부분을 추가하여 수신 인터페이스를 명확히 지정합니다.
    mtp_dest: "192.168.131.1"

    # --- 포트 번호 고정 ---
    # 0 대신 다른 프로그램이 사용하지 않을 만한 높은 포트 번호로 지정
    lidar_port: 45001
    imu_port: 45002

    # --- 필수 프레임 설정 ---
    sensor_frame: os_sensor
    lidar_frame: os_lidar
    imu_frame: os_imu
    
    # --- 데이터 타입 및 QoS ---
    point_type: xyzir
    use_system_default_qos: false